package com.hc.gqgs.mybatis.mapper;

import com.hc.gqgs.mybatis.po.BusinessRecord;
import com.hc.gqgs.mybatis.po.BusinessRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int countByExample(BusinessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByExample(BusinessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insert(BusinessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insertSelective(BusinessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    List<BusinessRecord> selectByExample(BusinessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    BusinessRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") BusinessRecord record, @Param("example") BusinessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExample(@Param("record") BusinessRecord record, @Param("example") BusinessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKeySelective(BusinessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_record
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKey(BusinessRecord record);
}