package com.hc.gqgs.mybatis.mapper;

import com.hc.gqgs.mybatis.po.LearnData;
import com.hc.gqgs.mybatis.po.LearnDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LearnDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int countByExample(LearnDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByExample(LearnDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByPrimaryKey(Integer dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insert(LearnData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insertSelective(LearnData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    List<LearnData> selectByExample(LearnDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    LearnData selectByPrimaryKey(Integer dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") LearnData record, @Param("example") LearnDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExample(@Param("record") LearnData record, @Param("example") LearnDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKeySelective(LearnData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKey(LearnData record);
}