package com.hc.gqgs.mybatis.mapper;

import com.hc.gqgs.mybatis.po.PersonalDetails;
import com.hc.gqgs.mybatis.po.PersonalDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonalDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int countByExample(PersonalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByExample(PersonalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insert(PersonalDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insertSelective(PersonalDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    List<PersonalDetails> selectByExample(PersonalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    PersonalDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") PersonalDetails record, @Param("example") PersonalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExample(@Param("record") PersonalDetails record, @Param("example") PersonalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKeySelective(PersonalDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_details
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKey(PersonalDetails record);
}