package com.hc.gqgs.mybatis.mapper;

import com.hc.gqgs.mybatis.po.RadioOption;
import com.hc.gqgs.mybatis.po.RadioOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RadioOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int countByExample(RadioOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int deleteByExample(RadioOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int deleteByPrimaryKey(Integer optionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int insert(RadioOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int insertSelective(RadioOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    List<RadioOption> selectByExample(RadioOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    RadioOption selectByPrimaryKey(Integer optionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") RadioOption record, @Param("example") RadioOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int updateByExample(@Param("record") RadioOption record, @Param("example") RadioOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int updateByPrimaryKeySelective(RadioOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_option
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int updateByPrimaryKey(RadioOption record);
}