package com.hc.gqgs.mybatis.mapper;

import com.hc.gqgs.mybatis.po.RadioQuestion;
import com.hc.gqgs.mybatis.po.RadioQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RadioQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int countByExample(RadioQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByExample(RadioQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insert(RadioQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insertSelective(RadioQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    List<RadioQuestion> selectByExample(RadioQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    RadioQuestion selectByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") RadioQuestion record, @Param("example") RadioQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExample(@Param("record") RadioQuestion record, @Param("example") RadioQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKeySelective(RadioQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radio_question
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKey(RadioQuestion record);
}