package com.hc.gqgs.mybatis.mapper;

import com.hc.gqgs.mybatis.po.SecondVisa;
import com.hc.gqgs.mybatis.po.SecondVisaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondVisaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int countByExample(SecondVisaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByExample(SecondVisaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insert(SecondVisa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insertSelective(SecondVisa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    List<SecondVisa> selectByExample(SecondVisaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    SecondVisa selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") SecondVisa record, @Param("example") SecondVisaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExample(@Param("record") SecondVisa record, @Param("example") SecondVisaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKeySelective(SecondVisa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_visa
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKey(SecondVisa record);
}