package com.hc.gqgs.mybatis.mapper;

import com.hc.gqgs.mybatis.po.TResource;
import com.hc.gqgs.mybatis.po.TResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int countByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insert(TResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insertSelective(TResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    List<TResource> selectByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    TResource selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TResource record, @Param("example") TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExample(@Param("record") TResource record, @Param("example") TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKeySelective(TResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKey(TResource record);
}