package com.hc.gqgs.mybatis.mapper;

import com.hc.gqgs.mybatis.po.TRoleResource;
import com.hc.gqgs.mybatis.po.TRoleResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int countByExample(TRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByExample(TRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insert(TRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int insertSelective(TRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    List<TRoleResource> selectByExample(TRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    TRoleResource selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TRoleResource record, @Param("example") TRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByExample(@Param("record") TRoleResource record, @Param("example") TRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKeySelective(TRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    int updateByPrimaryKey(TRoleResource record);
}