package com.hc.gqgs.mybatis.mapper;

import com.hc.gqgs.mybatis.po.UserOwn;
import com.hc.gqgs.mybatis.po.UserOwnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOwnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int countByExample(UserOwnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int deleteByExample(UserOwnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int insert(UserOwn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int insertSelective(UserOwn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    List<UserOwn> selectByExample(UserOwnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    UserOwn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserOwn record, @Param("example") UserOwnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int updateByExample(@Param("record") UserOwn record, @Param("example") UserOwnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int updateByPrimaryKeySelective(UserOwn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_own
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    int updateByPrimaryKey(UserOwn record);
}