package com.hc.gqgs.mybatis.po;

public class BusinessRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_record.id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_record.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String appeidcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_record.code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_record.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_record.id
     *
     * @return the value of business_record.id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_record.id
     *
     * @param id the value for business_record.id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_record.appeidcode
     *
     * @return the value of business_record.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getAppeidcode() {
        return appeidcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_record.appeidcode
     *
     * @param appeidcode the value for business_record.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setAppeidcode(String appeidcode) {
        this.appeidcode = appeidcode == null ? null : appeidcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_record.code
     *
     * @return the value of business_record.code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_record.code
     *
     * @param code the value for business_record.code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_record.state
     *
     * @return the value of business_record.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_record.state
     *
     * @param state the value for business_record.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }
}