package com.hc.gqgs.mybatis.po;

import java.util.Date;

public class CoupleAwart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String appeidcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.open_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.c_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String cCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.info_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String infoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.hk_photo_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String hkPhotoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.idCard_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String idcardPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.picture_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String picturePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.mc_picture3
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String mcPicture3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.time
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.police_station_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer policeStationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.remark
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couple_awart.sign
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String sign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.tid
     *
     * @return the value of couple_awart.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.tid
     *
     * @param tid the value for couple_awart.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.appeidcode
     *
     * @return the value of couple_awart.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getAppeidcode() {
        return appeidcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.appeidcode
     *
     * @param appeidcode the value for couple_awart.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setAppeidcode(String appeidcode) {
        this.appeidcode = appeidcode == null ? null : appeidcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.open_id
     *
     * @return the value of couple_awart.open_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.open_id
     *
     * @param openId the value for couple_awart.open_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.c_code
     *
     * @return the value of couple_awart.c_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getcCode() {
        return cCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.c_code
     *
     * @param cCode the value for couple_awart.c_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setcCode(String cCode) {
        this.cCode = cCode == null ? null : cCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.info_path
     *
     * @return the value of couple_awart.info_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getInfoPath() {
        return infoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.info_path
     *
     * @param infoPath the value for couple_awart.info_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setInfoPath(String infoPath) {
        this.infoPath = infoPath == null ? null : infoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.path
     *
     * @return the value of couple_awart.path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.path
     *
     * @param path the value for couple_awart.path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.data
     *
     * @return the value of couple_awart.data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.data
     *
     * @param data the value for couple_awart.data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.hk_photo_path
     *
     * @return the value of couple_awart.hk_photo_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getHkPhotoPath() {
        return hkPhotoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.hk_photo_path
     *
     * @param hkPhotoPath the value for couple_awart.hk_photo_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setHkPhotoPath(String hkPhotoPath) {
        this.hkPhotoPath = hkPhotoPath == null ? null : hkPhotoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.idCard_path
     *
     * @return the value of couple_awart.idCard_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getIdcardPath() {
        return idcardPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.idCard_path
     *
     * @param idcardPath the value for couple_awart.idCard_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setIdcardPath(String idcardPath) {
        this.idcardPath = idcardPath == null ? null : idcardPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.picture_path
     *
     * @return the value of couple_awart.picture_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.picture_path
     *
     * @param picturePath the value for couple_awart.picture_path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath == null ? null : picturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.mc_picture3
     *
     * @return the value of couple_awart.mc_picture3
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getMcPicture3() {
        return mcPicture3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.mc_picture3
     *
     * @param mcPicture3 the value for couple_awart.mc_picture3
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setMcPicture3(String mcPicture3) {
        this.mcPicture3 = mcPicture3 == null ? null : mcPicture3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.state
     *
     * @return the value of couple_awart.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.state
     *
     * @param state the value for couple_awart.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.time
     *
     * @return the value of couple_awart.time
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.time
     *
     * @param time the value for couple_awart.time
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.police_station_id
     *
     * @return the value of couple_awart.police_station_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getPoliceStationId() {
        return policeStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.police_station_id
     *
     * @param policeStationId the value for couple_awart.police_station_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setPoliceStationId(Integer policeStationId) {
        this.policeStationId = policeStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.remark
     *
     * @return the value of couple_awart.remark
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.remark
     *
     * @param remark the value for couple_awart.remark
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couple_awart.sign
     *
     * @return the value of couple_awart.sign
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couple_awart.sign
     *
     * @param sign the value for couple_awart.sign
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }
}