package com.hc.gqgs.mybatis.po;

public class LearnData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_data.data_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_data.title
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_data.video_url
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_data.video_screenshot
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String videoScreenshot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_data.data_id
     *
     * @return the value of learn_data.data_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_data.data_id
     *
     * @param dataId the value for learn_data.data_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_data.title
     *
     * @return the value of learn_data.title
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_data.title
     *
     * @param title the value for learn_data.title
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_data.video_url
     *
     * @return the value of learn_data.video_url
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_data.video_url
     *
     * @param videoUrl the value for learn_data.video_url
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_data.video_screenshot
     *
     * @return the value of learn_data.video_screenshot
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getVideoScreenshot() {
        return videoScreenshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_data.video_screenshot
     *
     * @param videoScreenshot the value for learn_data.video_screenshot
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setVideoScreenshot(String videoScreenshot) {
        this.videoScreenshot = videoScreenshot == null ? null : videoScreenshot.trim();
    }
}