package com.hc.gqgs.mybatis.po;

import java.util.Date;

public class PersonalDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_details.id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_details.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String appeidcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_details.name
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_details.sex
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_details.birthtime
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Date birthtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_details.idcard
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_details.telphone
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_details.nation
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_details.domicile
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String domicile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_details.current_address
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String currentAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_details.id
     *
     * @return the value of personal_details.id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_details.id
     *
     * @param id the value for personal_details.id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_details.appeidcode
     *
     * @return the value of personal_details.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getAppeidcode() {
        return appeidcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_details.appeidcode
     *
     * @param appeidcode the value for personal_details.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setAppeidcode(String appeidcode) {
        this.appeidcode = appeidcode == null ? null : appeidcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_details.name
     *
     * @return the value of personal_details.name
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_details.name
     *
     * @param name the value for personal_details.name
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_details.sex
     *
     * @return the value of personal_details.sex
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_details.sex
     *
     * @param sex the value for personal_details.sex
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_details.birthtime
     *
     * @return the value of personal_details.birthtime
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Date getBirthtime() {
        return birthtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_details.birthtime
     *
     * @param birthtime the value for personal_details.birthtime
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setBirthtime(Date birthtime) {
        this.birthtime = birthtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_details.idcard
     *
     * @return the value of personal_details.idcard
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_details.idcard
     *
     * @param idcard the value for personal_details.idcard
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_details.telphone
     *
     * @return the value of personal_details.telphone
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_details.telphone
     *
     * @param telphone the value for personal_details.telphone
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_details.nation
     *
     * @return the value of personal_details.nation
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_details.nation
     *
     * @param nation the value for personal_details.nation
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_details.domicile
     *
     * @return the value of personal_details.domicile
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getDomicile() {
        return domicile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_details.domicile
     *
     * @param domicile the value for personal_details.domicile
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setDomicile(String domicile) {
        this.domicile = domicile == null ? null : domicile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_details.current_address
     *
     * @return the value of personal_details.current_address
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getCurrentAddress() {
        return currentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_details.current_address
     *
     * @param currentAddress the value for personal_details.current_address
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setCurrentAddress(String currentAddress) {
        this.currentAddress = currentAddress == null ? null : currentAddress.trim();
    }
}