package com.hc.gqgs.mybatis.po;

public class PoliceStation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column police_station.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column police_station.police_station
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String policeStation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column police_station.tid
     *
     * @return the value of police_station.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column police_station.tid
     *
     * @param tid the value for police_station.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column police_station.police_station
     *
     * @return the value of police_station.police_station
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getPoliceStation() {
        return policeStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column police_station.police_station
     *
     * @param policeStation the value for police_station.police_station
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setPoliceStation(String policeStation) {
        this.policeStation = policeStation == null ? null : policeStation.trim();
    }
}