package com.hc.gqgs.mybatis.po;

public class RadioOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radio_option.option_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private Integer optionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radio_option.question_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radio_option.options
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String options;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radio_option.option_id
     *
     * @return the value of radio_option.option_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public Integer getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radio_option.option_id
     *
     * @param optionId the value for radio_option.option_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setOptionId(Integer optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radio_option.question_id
     *
     * @return the value of radio_option.question_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radio_option.question_id
     *
     * @param questionId the value for radio_option.question_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radio_option.options
     *
     * @return the value of radio_option.options
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getOptions() {
        return options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radio_option.options
     *
     * @param options the value for radio_option.options
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setOptions(String options) {
        this.options = options == null ? null : options.trim();
    }
}