package com.hc.gqgs.mybatis.po;

import java.util.Date;

public class SecondVisa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String appeidcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.open_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.s_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String sCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.photoPath
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String photopath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.time
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.remark
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.xgAndAmMuch
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer xgandammuch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.orderNum
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.id_card
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_visa.sign
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String sign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.tid
     *
     * @return the value of second_visa.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.tid
     *
     * @param tid the value for second_visa.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.appeidcode
     *
     * @return the value of second_visa.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getAppeidcode() {
        return appeidcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.appeidcode
     *
     * @param appeidcode the value for second_visa.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setAppeidcode(String appeidcode) {
        this.appeidcode = appeidcode == null ? null : appeidcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.open_id
     *
     * @return the value of second_visa.open_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.open_id
     *
     * @param openId the value for second_visa.open_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.s_code
     *
     * @return the value of second_visa.s_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getsCode() {
        return sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.s_code
     *
     * @param sCode the value for second_visa.s_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setsCode(String sCode) {
        this.sCode = sCode == null ? null : sCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.state
     *
     * @return the value of second_visa.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.state
     *
     * @param state the value for second_visa.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.data
     *
     * @return the value of second_visa.data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.data
     *
     * @param data the value for second_visa.data
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.path
     *
     * @return the value of second_visa.path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.path
     *
     * @param path the value for second_visa.path
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.photoPath
     *
     * @return the value of second_visa.photoPath
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getPhotopath() {
        return photopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.photoPath
     *
     * @param photopath the value for second_visa.photoPath
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setPhotopath(String photopath) {
        this.photopath = photopath == null ? null : photopath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.time
     *
     * @return the value of second_visa.time
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.time
     *
     * @param time the value for second_visa.time
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.remark
     *
     * @return the value of second_visa.remark
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.remark
     *
     * @param remark the value for second_visa.remark
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.xgAndAmMuch
     *
     * @return the value of second_visa.xgAndAmMuch
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getXgandammuch() {
        return xgandammuch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.xgAndAmMuch
     *
     * @param xgandammuch the value for second_visa.xgAndAmMuch
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setXgandammuch(Integer xgandammuch) {
        this.xgandammuch = xgandammuch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.orderNum
     *
     * @return the value of second_visa.orderNum
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.orderNum
     *
     * @param ordernum the value for second_visa.orderNum
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setOrdernum(String ordernum) {
        this.ordernum = ordernum == null ? null : ordernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.id_card
     *
     * @return the value of second_visa.id_card
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.id_card
     *
     * @param idCard the value for second_visa.id_card
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_visa.sign
     *
     * @return the value of second_visa.sign
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_visa.sign
     *
     * @param sign the value for second_visa.sign
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }
}