package com.hc.gqgs.mybatis.po;

public class TAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_user
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String adminUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_pwd
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String adminPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.user_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.role_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.status
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.police_station_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String policeStationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.tid
     *
     * @return the value of t_admin.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.tid
     *
     * @param tid the value for t_admin.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_user
     *
     * @return the value of t_admin.admin_user
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getAdminUser() {
        return adminUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_user
     *
     * @param adminUser the value for t_admin.admin_user
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setAdminUser(String adminUser) {
        this.adminUser = adminUser == null ? null : adminUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_pwd
     *
     * @return the value of t_admin.admin_pwd
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getAdminPwd() {
        return adminPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_pwd
     *
     * @param adminPwd the value for t_admin.admin_pwd
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setAdminPwd(String adminPwd) {
        this.adminPwd = adminPwd == null ? null : adminPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.user_code
     *
     * @return the value of t_admin.user_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.user_code
     *
     * @param userCode the value for t_admin.user_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.role_code
     *
     * @return the value of t_admin.role_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.role_code
     *
     * @param roleCode the value for t_admin.role_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.status
     *
     * @return the value of t_admin.status
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.status
     *
     * @param status the value for t_admin.status
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.police_station_id
     *
     * @return the value of t_admin.police_station_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getPoliceStationId() {
        return policeStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.police_station_id
     *
     * @param policeStationId the value for t_admin.police_station_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setPoliceStationId(String policeStationId) {
        this.policeStationId = policeStationId == null ? null : policeStationId.trim();
    }
}