package com.hc.gqgs.mybatis.po;

public class TResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.name
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String resourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.permission_url
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String permissionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.operation
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.permission
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.tid
     *
     * @return the value of t_resource.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.tid
     *
     * @param tid the value for t_resource.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.name
     *
     * @return the value of t_resource.name
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.name
     *
     * @param name the value for t_resource.name
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_code
     *
     * @return the value of t_resource.resource_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getResourceCode() {
        return resourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_code
     *
     * @param resourceCode the value for t_resource.resource_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setResourceCode(String resourceCode) {
        this.resourceCode = resourceCode == null ? null : resourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.permission_url
     *
     * @return the value of t_resource.permission_url
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.permission_url
     *
     * @param permissionUrl the value for t_resource.permission_url
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl == null ? null : permissionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.operation
     *
     * @return the value of t_resource.operation
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.operation
     *
     * @param operation the value for t_resource.operation
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.permission
     *
     * @return the value of t_resource.permission
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.permission
     *
     * @param permission the value for t_resource.permission
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }
}