package com.hc.gqgs.mybatis.po;

public class TRoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.role_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.resource_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String resourceCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.tid
     *
     * @return the value of t_role_resource.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.tid
     *
     * @param tid the value for t_role_resource.tid
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.role_code
     *
     * @return the value of t_role_resource.role_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.role_code
     *
     * @param roleCode the value for t_role_resource.role_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.resource_code
     *
     * @return the value of t_role_resource.resource_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getResourceCode() {
        return resourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.resource_code
     *
     * @param resourceCode the value for t_role_resource.resource_code
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setResourceCode(String resourceCode) {
        this.resourceCode = resourceCode == null ? null : resourceCode.trim();
    }
}