package com.hc.gqgs.mybatis.po;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.biz_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String appeidcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.biz_id
     *
     * @return the value of user_info.biz_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.biz_id
     *
     * @param bizId the value for user_info.biz_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setBizId(String bizId) {
        this.bizId = bizId == null ? null : bizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.state
     *
     * @return the value of user_info.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.state
     *
     * @param state the value for user_info.state
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.appeidcode
     *
     * @return the value of user_info.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getAppeidcode() {
        return appeidcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.appeidcode
     *
     * @param appeidcode the value for user_info.appeidcode
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setAppeidcode(String appeidcode) {
        this.appeidcode = appeidcode == null ? null : appeidcode.trim();
    }
}