package com.hc.gqgs.mybatis.po;

public class UserOwn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.user_name
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.sex
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.birthday
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.id_card
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.address
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.email
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.mobile_no
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String mobileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.car_type
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.biz_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.wx_open_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String wxOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_own.time
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.id
     *
     * @return the value of user_own.id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.id
     *
     * @param id the value for user_own.id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.user_name
     *
     * @return the value of user_own.user_name
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.user_name
     *
     * @param userName the value for user_own.user_name
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.sex
     *
     * @return the value of user_own.sex
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.sex
     *
     * @param sex the value for user_own.sex
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.birthday
     *
     * @return the value of user_own.birthday
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.birthday
     *
     * @param birthday the value for user_own.birthday
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.id_card
     *
     * @return the value of user_own.id_card
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.id_card
     *
     * @param idCard the value for user_own.id_card
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.address
     *
     * @return the value of user_own.address
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.address
     *
     * @param address the value for user_own.address
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.email
     *
     * @return the value of user_own.email
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.email
     *
     * @param email the value for user_own.email
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.mobile_no
     *
     * @return the value of user_own.mobile_no
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.mobile_no
     *
     * @param mobileNo the value for user_own.mobile_no
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.car_type
     *
     * @return the value of user_own.car_type
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.car_type
     *
     * @param carType the value for user_own.car_type
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.biz_id
     *
     * @return the value of user_own.biz_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.biz_id
     *
     * @param bizId the value for user_own.biz_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setBizId(String bizId) {
        this.bizId = bizId == null ? null : bizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.wx_open_id
     *
     * @return the value of user_own.wx_open_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.wx_open_id
     *
     * @param wxOpenId the value for user_own.wx_open_id
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId == null ? null : wxOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_own.time
     *
     * @return the value of user_own.time
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_own.time
     *
     * @param time the value for user_own.time
     *
     * @mbggenerated Tue Mar 06 19:24:21 CST 2018
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}