package com.hc.gqgs.mybatis.po;

public class WxManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_manage.id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_manage.wx_open_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private String wxOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_manage.type
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_manage.policstation
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    private Integer policstation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_manage.id
     *
     * @return the value of wx_manage.id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_manage.id
     *
     * @param id the value for wx_manage.id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_manage.wx_open_id
     *
     * @return the value of wx_manage.wx_open_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_manage.wx_open_id
     *
     * @param wxOpenId the value for wx_manage.wx_open_id
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId == null ? null : wxOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_manage.type
     *
     * @return the value of wx_manage.type
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_manage.type
     *
     * @param type the value for wx_manage.type
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_manage.policstation
     *
     * @return the value of wx_manage.policstation
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public Integer getPolicstation() {
        return policstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_manage.policstation
     *
     * @param policstation the value for wx_manage.policstation
     *
     * @mbggenerated Sun Mar 11 17:45:24 CST 2018
     */
    public void setPolicstation(Integer policstation) {
        this.policstation = policstation;
    }
}